// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MASA.IoT.WebApi.Models.Models;

public partial class IoTDevicewares
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(50)]
    public string UUID { get; set; }

    [Required]
    [StringLength(20)]
    public string ProductCode { get; set; }

    [Required]
    [StringLength(20)]
    public string DeviceName { get; set; }

    public DateTime CreationTime { get; set; }
}