// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Masa.BuildingBlocks.Ddd.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace MASA.IoT.WebApi.Models;

public partial class IoTDeviceInfo : AggregateRoot<Guid>
{
    [Key]
    public Guid Id { get; set; }

    public DateTime CreationTime { get; set; }

    public DateTime LastModificationTime { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime DeletionTime { get; set; }

    [Required]
    [StringLength(50)]
    public string DeviceName { get; set; }

    public Guid ProductInfoId { get; set; }

    [ForeignKey("ProductInfoId")]
    [InverseProperty("IoTDeviceInfo")]
    public virtual IoTProductInfo ProductInfo { get; set; }
}