// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Masa.BuildingBlocks.Ddd.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace MASA.IoT.WebApi.Models;

public partial class IoTProductInfo : AggregateRoot<Guid>
{
    [Key]
    public Guid Id { get; set; }

    public DateTime CreationTime { get; set; }

    public DateTime LastModificationTime { get; set; }

    [Required]
    [StringLength(50)]
    public string SalesName { get; set; }

    [Required]
    [StringLength(50)]
    public string MaterialNo { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime DeletionTime { get; set; }

    [InverseProperty("ProductInfo")]
    public virtual ICollection<IoTDeviceInfo> IoTDeviceInfo { get; } = new List<IoTDeviceInfo>();
}