// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MASA.IoT.WebApi.Models.Models;

public partial class IoTDeviceInfo
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(50)]
    public string DeviceName { get; set; }

    public Guid ProductInfoId { get; set; }

    [Required]
    [StringLength(50)]
    public string Password { get; set; }

    [InverseProperty("DeviceInfo")]
    public virtual IoTDeviceExtend IoTDeviceExtend { get; set; }

    [ForeignKey("ProductInfoId")]
    [InverseProperty("IoTDeviceInfo")]
    public virtual IoTProductInfo ProductInfo { get; set; }
}