// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MASA.IoT.WebApi.Models.Models;

public partial class IoTDeviceExtend
{
    [Key]
    public Guid DeviceInfoId { get; set; }

    public int OnLineStates { get; set; }

    [ForeignKey("DeviceInfoId")]
    [InverseProperty("IoTDeviceExtend")]
    public virtual IoTDeviceInfo DeviceInfo { get; set; }
}